quiz = [{
	        "question"      :   "I turisti viaggiano in modo",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['irregolare', 'regolare'],
	        "correct"       :   "irregolare",
	        "explanation"   :   "",
	    },{
	        "question"      :   "I turisti viaggiano",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['non per ottenere un reddito', 'per ottenere un reddito'],
	        "correct"       :   "non per ottenere un reddito",
	        "explanation"   :   "",
	    },{
	        "question"      :   "I turisti",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['pernottano', 'non pernottano'],
	        "correct"       :   "pernottano",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Gli escursionisti",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['pernottano', 'non pernottano'],
	        "correct"       :   "pernottano",
	        "explanation"   :   "",
	    },{
	        "question"      :   "I viaggi leisure sono",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['viaggi di piacere', "viaggi d'affari"],
	        "correct"       :   "viaggi di piacere",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Il turismo contrende le relazioni tra",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['turisti, ambiente, residenti e operatori economici del settore', 'turisti e operatori economici del settore'],
	        "correct"       :   "turisti, ambiente, residenti e operatori economici del settore",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Il turismo produttivo è formato da",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['operatori economici del settore', 'turisti', 'residenti', 'ambiente'],
	        "correct"       :   "operatori economici del settore",
	        "explanation"   :   "",
	    },{
	        "question"      :   "I turisti italiani che viaggiano in Italia fanno parte del turismo",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['domestico', 'interno', 'nazionale', 'internazionale'],
	        "correct"       :   "domestico",
	        "explanation"   :   "",
	    },{
	        "question"      :   "i turisti italiani e stranieri che viaggiano in ITALIA fanno parte del turismo",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['interno', 'domestico', 'nazionale', 'internazionale'],
	        "correct"       :   "interno",
	        "explanation"   :   "",
	    },{
	        "question"      :   "i turisti italiani che viaggiano in ITALIA ed ESTERO fanno parte del turismo",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['nazionale', 'domestico', 'interno', 'internazionale'],
	        "correct"       :   "nazionale",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Tutti i turisti che oltrepassano la frontiera fanno parte del turismo",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['internazionale', 'domestico', 'interno', 'nazionale'],
	        "correct"       :   "internazionale",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Le attività offerte al turista in entrata in un Paese fanno parte del",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['turismo produttivo incoming', 'turismo produttivo outgoing'],
	        "correct"       :   "turismo produttivo incoming",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Le attività offerte al turista in uscita da un Paese fanno parte del",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['turismo produttivo outgoing', 'turismo produttivo incoming'],
	        "correct"       :   "turismo produttivo outgoing",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Quali sono gli effetti negativi del turismo per i residenti",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['inquinamento ed aumento dei prezzi', 'riduzione del reddito', "riduzione dell'occupazione", 'peggioramento del livello di benessere'],
	        "correct"       :   "inquinamento ed aumento dei prezzi",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Il turismo sostenibile mira a",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ["favorire un turismo che non altera l'ambiente", 'sostenere le imprese che inquinano'],
	        "correct"       :   "favorire un turismo che non altera l'ambiente",
	        "explanation"   :   "",
	    },{
	        "question"      :   "Il bisogno è",
	        "image"         :   "https://tuocoach.files.wordpress.com/2018/11/cambiamento-10.jpg?w=345&h=294",
	        "choices"       :   ['uno stato di insoddisfazione', 'uno stato di soddisfazione'],
	        "correct"       :   "uno stato di insoddisfazione",
	        "explanation"   :   "",
	    },];